version: "3.9"

services:
  archiver:
    build: .
    command: "uvicorn server:app --port 8088 --host 0.0.0.0 --reload"
    volumes:
      - .:/code
    ports:
      - "8088:8088"
    restart: on-failure